### ISSUE TITLE
The naming convention does not match the official documentation.

### ISSUE THREAD

**Issue by ArturWroblewski** [SamuelAsherRivello/godot-project-template#1]
The naming convention does not match the official documentation. 

link:
https://docs.godotengine.org/en/stable/tutorials/best_practices/project_organization.html

**Style guide**

For consistency across projects, we recommend following these guidelines:

- Use snake_case for folder and file names (with the exception of C# scripts). This sidesteps case sensitivity issues that can crop up after exporting a project on Windows. C# scripts are an exception to this rule, as the convention is to name them after the class name which should be in PascalCase.

- Use PascalCase for node names, as this matches built-in node casing.

- In general, keep third-party resources in a top-level addons/ folder, even if they aren't editor plugins. This makes it easier to track which files are third-party. There are some exceptions to this rule; for instance, if you use third-party game assets for a character, it makes more sense to include them within the same folder as the character scenes and scripts.

**Available solution:**
- update folder naming with lowercase letters
- contact godot and change the convention on their website to ensure consistency. Maybe you have a better suggestion.

**Comment by SamuelAsherRivello** [comment]
Hello! Thanks for your interest.

I don't promote this repo to "match the official documentation." I'm not interested to make changes.

Best wishes!
